# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd3b5bf20132a1f23fcb08dafc4a896e1482391cb8082c2ba776184aea32cc7da5b283bfb8309b07bffd7e910f8496d01bce678b2d40a73d3eab226ea7e3843

test:
  secret_key_base: b00412ceaaa7f4923d3d0e376ebb872e73b0a1b549a194b8b241ad33de6508c59e3ae1738020110862542d6564316f7f1e7a21f3d9fe97558d8203462e0c3b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
